name: Deploy eshop to AWS

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Deploy:
    #Deploy eshop to AWS
    # needs: [Build, Test]
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install packages
        run: pip3 install ansible==4.0 boto boto3

      - name: Add SSH key
        run: |
          touch ./ansible/devops.pem
          echo '${{ secrets.SSH_KEY }}' >> ./ansible/devops.pem
          chmod 400 ./ansible/devops.pem

      - name: Setup env and run ansible
        run: echo setup-env
        env:
          ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          SECURITY_TOKEN: ${{ secrets.AWS_SECURITY_TOKEN }}
          ANSIBLE_HOST_KEY_CHECKING: False

      - name: Run ansible
        run: |
          ansible-playbook ./ansible/ec2_deploy.yml --user ec2-user --key-file ./ansible/devops.pem
